name: generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  build:
  source_gen:
  analyzer: ^6.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_test:
  build_runner:
