targets:
  $default:
    builders:
      alvic_tools:
        enabled: true

builders:
  alvic_tools:
    import: "package:alvic_tools/builder.dart"
    builder_factories: ["restRepositoryGenerator"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]