name: alvic_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.

dependencies:
  build:
  source_gen:
  analyzer: ^6.2.0
  get_it: ^7.6.4
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_test:
  build_runner:
